### ISSUE TITLE
Set Time

### ISSUE THREAD

**Issue by Sayed94h** [razvanbrb/Pomofocus#10]
## 2. User story : Set time

**As a user I would like be able to set the time to study base on promodo technique and set a time for long break and short break**

**Assigned to Sayed**

- \_Given [context] when [a specific action is performed] then [a set of consequences should occur]\_\_

### REPO

- This user story is developed on branch `set-time`.

- This branch is merged to `master` branch after completion.

### Task A: CSS

- [x] Added style attributes inside functions to change the style by running the function

### Task B: HTML

- [x] Update textContent of some elements by running the function

### Task C: JavaScript

- [x] Created functions to change the style
- [x] Created functions to make the timer work
- [x] Created variables and stored HTML elements inside

### Task D: Development Strategy

- [x] Wrote the development-strategy part for this branch

### Task E: Issues

- [x] Created an issue for this user story

### Tast F: PR

- [x] Create a PR and assigned reviewers

---
